### ISSUE TITLE
k8s env vars not set by default

### ISSUE THREAD

**Issue by grantr** [grantr/helloworld-crd#4]
The vars referenced in `print-workspace-status.sh` are not documented or defaulted, leading to failures when trying to deploy to a cluster.

The default for `STABLE_K8S_cluster seems like it can be `kubectl config current-context`. I'm not sure what the default for `STABLE_DOCKER_REPO` should be.

/cc @mattmoor

**Comment by mattmoor** [comment]
They're documented here: https://github.com/grantr/helloworld-crd#running-on-cluster

We can default them if we want (see [here](https://github.com/kubernetes/test-infra/blob/master/print-workspace-status.sh#L20)), but defaulting to `kubectl config current-context` could lead to strange behaviors.

**Comment by mattmoor** [comment]
We could construct something for `STABLE_DOCKER_REPO` based on the current `gcloud` project?

**Comment by grantr** [comment]
Oops sorry I missed those docs! #7 seems like a good approach for adding further details.
