### ISSUE TITLE
Bazel-built image fails to run missing libstdc++

### ISSUE THREAD

**Issue by grantr** [grantr/helloworld-crd#8]
For some reason the Bazel-built binary on my machine wants to link to `libstdc++` and it's not available in the image.

```
/app//sample-controller: error while loading shared libraries: libstdc++.so.6: cannot open shared object file: No such file or directory      
```

I see this on both minikube and GKE clusters.

**Comment by mattmoor** [comment]
We want [this line](https://github.com/kubernetes/test-infra/blob/master/prow/cmd/horologium/BUILD#L23)

**Comment by grantr** [comment]
:+1: That fixed the issue for me.
